apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: test
spec:
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/test/helloworld
        env:
        env:
        - name: TARGET
          value: "Go Sample v1"
